/* generated by tools/build-release.js — do not edit by hand */
var BUILD = '20260825-1325';
var CACHE = 'pp-' + BUILD;
var PRECACHE = [
  "./nba-perfect-player.html",
  "./assets/fonts/fredoka-latin.woff2",
  "./assets/fonts/nunito-latin.woff2",
  "./assets/css/fonts.css",
  "./assets/js/perfect-player-boot.min.js?v=20260825-1325",
  "./assets/css/perfect-player.css?v=20260825-1325",
  "./assets/css/perfect-player-premium.css?v=20260825-1325",
  "./assets/js/hupu/script-00-2678-58zyeprc-upload-1783508428855-12.min.js",
  "./assets/js/hupu/script-01-2678-5hu3djrc-upload-1783494754597-12.min.js",
  "./assets/js/current-player-ratings-2026.min.js",
  "./assets/js/hupu/script-02-2678-gd4jvxrc-upload-1783494754597-15.min.js",
  "./assets/js/hupu/script-03-2678-456sfprc-upload-1783494754597-18.min.js",
  "./assets/js/hupu/script-04-2678-mdo4zerc-upload-1783494754597-21.min.js",
  "./assets/js/hupu/script-05-2678-qlg35lrc-upload-1783494754597-24.min.js",
  "./assets/js/perfect-player-core.min.js?v=20260825-1325",
  "./assets/js/perfect-player-era-mode.min.js?v=20260825-1325",
  "./assets/js/perfect-player-era-draft.min.js?v=20260825-1325",
  "./assets/js/perfect-player-event-runtime.min.js?v=20260825-1325",
  "./assets/js/perfect-player-poster.min.js?v=20260825-1325"
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (c) {
      return Promise.allSettled(PRECACHE.map(function (u) { return c.add(u); }));
    }).then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  if (req.headers.has('range')) return;
  var url = new URL(req.url);
  if (url.origin !== location.origin) return;

  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req).then(function (r) {
        var copy = r.clone();
        caches.open(CACHE).then(function (c) { c.put(req, copy); });
        return r;
      }).catch(function () {
        return caches.match(req).then(function (hit) {
          return hit || caches.match('./nba-perfect-player.html');
        });
      })
    );
    return;
  }

  if (!/\.(?:js|css|woff2|json|png|jpe?g|svg|webp|gif|ico)(?:\?|$)/.test(url.pathname)) return;
  e.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (r) {
        if (r && r.ok) {
          var copy = r.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return r;
      });
    })
  );
});
