/**
 * build-release.js — 发布构建：
 *  1. terser 压缩运行时 JS → *.min.js
 *  2. 统一 stamp 版本号 ?v=BUILD（html + boot.min + era-mode.min）
 *  3. 重新生成 sw.js（BUILD + 预缓存清单）
 * 用法：node tools/build-release.js
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const MINIFY = [
  'assets/js/perfect-player-boot.js',
  'assets/js/hupu/script-00-2678-58zyeprc-upload-1783508428855-12.js',
  'assets/js/hupu/script-01-2678-5hu3djrc-upload-1783494754597-12.js',
  'assets/js/current-player-ratings-2026.js',
  'assets/js/hupu/script-02-2678-gd4jvxrc-upload-1783494754597-15.js',
  'assets/js/hupu/script-03-2678-456sfprc-upload-1783494754597-18.js',
  'assets/js/hupu/script-04-2678-mdo4zerc-upload-1783494754597-21.js',
  'assets/js/hupu/script-05-2678-qlg35lrc-upload-1783494754597-24.js',
  'assets/js/perfect-player-core.js',
  'assets/js/perfect-player-era-mode.js',
  'assets/js/perfect-player-era-draft.js',
  'assets/js/perfect-player-event-runtime.js',
  'assets/js/perfect-player-poster.js',
  'assets/js/perfect-player-hupu-extensions.js',
  'assets/js/perfect-player-skills.js',
  'assets/js/perfect-player-enhancements.js',
  'assets/js/perfect-player-event-library.js',
  'assets/js/perfect-player-story-events.js',
  'assets/js/perfect-player-hupu-life-events.js',
  'assets/js/perfect-player-legend-story.js',
  'assets/js/perfect-player-legend-challenge.js',
  'assets/js/perfect-player-awards.js',
  'assets/js/perfect-player-allstar.js',
  'assets/js/perfect-player-live-court.js',
  'assets/js/perfect-player-live-sim.js',
  'assets/js/hupu/legend-era/legend-era-1984-static.js',
  'assets/js/hupu/legend-era/legend-era-1996-static.js',
  'assets/js/hupu/legend-era/legend-era-2003-static.js',
  'assets/js/hupu/legend-era/era-config.js',
  'assets/js/hupu/legend-era/draft-classes.js',
  'assets/js/hupu/legend-era/historical-players.js',
  'assets/js/hupu/legend-era/era-bench-pools.js',
  'assets/js/hupu/legend-era/era-historical-births.js',
  'assets/js/hupu/legend-era/era-rosters.js',
  'assets/js/hupu/legend-era/hupu-player-photos.js',
];

const HTML = 'nba-perfect-player.html';
const d = new Date();
const BUILD = d.getFullYear() +
  String(d.getMonth() + 1).padStart(2, '0') + String(d.getDate()).padStart(2, '0') +
  '-' + String(d.getHours()).padStart(2, '0') + String(d.getMinutes()).padStart(2, '0');

function min(p) {
  return p.slice(0, -3) + '.min.js';
}

let rawTotal = 0, minTotal = 0;
for (const p of MINIFY) {
  const src = fs.readFileSync(p, 'utf8');
  const out = execSync('npx terser --compress passes=2 --mangle --ecma 5', {
    input: src, maxBuffer: 256 * 1024 * 1024,
  }).toString();
  fs.writeFileSync(min(p), out);
  rawTotal += src.length; minTotal += out.length;
  console.log(path.basename(p).padEnd(46) +
    (src.length / 1024).toFixed(0).padStart(7) + ' KB → ' +
    (out.length / 1024).toFixed(0).padStart(6) + ' KB');
}
console.log('---');
console.log('minify total: ' + (rawTotal / 1024 / 1024).toFixed(2) + ' MB → ' + (minTotal / 1024 / 1024).toFixed(2) + ' MB');

// stamp BUILD into html + minified loaders (sources keep old tokens; html ships stamped)
function stamp(p) {
  let s = fs.readFileSync(p, 'utf8');
  const before = s;
  s = s.replace(/v=\d{8}-[a-z0-9-]+/g, 'v=' + BUILD);
  if (s !== before) fs.writeFileSync(p, s);
}
stamp(HTML);
stamp(min('assets/js/perfect-player-boot.js'));
stamp(min('assets/js/perfect-player-era-mode.js'));
console.log('stamped v=' + BUILD);

// regenerate sw.js — precache kept MINIMAL (html + css + fonts) so the SW
// install never competes for bandwidth with page resources on slow links.
// JS/images are runtime-cached as the page naturally fetches them.
const html = fs.readFileSync(HTML, 'utf8');
const precache = new Set(['./nba-perfect-player.html']);
let m;
const re = /(?:src|href)="(assets\/(?:css|fonts)\/[^"]+)"/g;
while ((m = re.exec(html)) !== null) {
  const u = m[1];
  if (/\.(css|woff2)(\?|$)/.test(u)) precache.add('./' + u);
}
const sw = `/* generated by tools/build-release.js — do not edit by hand */
var BUILD = '${BUILD}';
var CACHE = 'pp-' + BUILD;
var PRECACHE = ${JSON.stringify(Array.from(precache), null, 2)};

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (c) {
      return Promise.allSettled(PRECACHE.map(function (u) { return c.add(u); }));
    }).then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  if (req.headers.has('range')) return;
  var url = new URL(req.url);
  if (url.origin !== location.origin) return;

  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req).then(function (r) {
        var copy = r.clone();
        caches.open(CACHE).then(function (c) { c.put(req, copy); });
        return r;
      }).catch(function () {
        return caches.match(req).then(function (hit) {
          return hit || caches.match('./nba-perfect-player.html');
        });
      })
    );
    return;
  }

  if (!/\\.(?:js|css|woff2|json|png|jpe?g|svg|webp|gif|ico)(?:\\?|$)/.test(url.pathname)) return;
  e.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (r) {
        if (r && r.ok) {
          var copy = r.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return r;
      });
    })
  );
});
`;
fs.writeFileSync('sw.js', sw);
console.log('sw.js regenerated (' + precache.size + ' precache entries)');
