/** 只重新生成 sw.js（沿用现有 BUILD，不动缓存命名，不重压缩） */
const fs = require('fs');

const sw = fs.readFileSync('sw.js', 'utf8');
const BUILD = (sw.match(/var BUILD = '([^']+)'/) || [])[1];
if (!BUILD) { console.error('no BUILD found'); process.exit(1); }

const html = fs.readFileSync('nba-perfect-player.html', 'utf8');
const precache = new Set(['./nba-perfect-player.html']);
let m;
const re = /(?:src|href)="(assets\/(?:css|fonts)\/[^"]+)"/g;
while ((m = re.exec(html)) !== null) {
  const u = m[1];
  if (/\.(css|woff2)(\?|$)/.test(u)) precache.add('./' + u);
}

const out = `/* generated by tools/build-release.js — do not edit by hand */
var BUILD = '${BUILD}';
var CACHE = 'pp-' + BUILD;
var PRECACHE = ${JSON.stringify(Array.from(precache), null, 2)};

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (c) {
      return Promise.allSettled(PRECACHE.map(function (u) { return c.add(u); }));
    }).then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  if (req.headers.has('range')) return;
  var url = new URL(req.url);
  if (url.origin !== location.origin) return;

  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req).then(function (r) {
        var copy = r.clone();
        caches.open(CACHE).then(function (c) { c.put(req, copy); });
        return r;
      }).catch(function () {
        return caches.match(req).then(function (hit) {
          return hit || caches.match('./nba-perfect-player.html');
        });
      })
    );
    return;
  }

  if (!/\\.(?:js|css|woff2|json|png|jpe?g|svg|webp|gif|ico)(?:\\?|$)/.test(url.pathname)) return;
  e.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (r) {
        if (r && r.ok) {
          var copy = r.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return r;
      });
    })
  );
});
`;
fs.writeFileSync('sw.js', out);
console.log('sw.js regenerated, BUILD=' + BUILD + ', precache=' + precache.size + ' entries (slim)');
